### ISSUE TITLE
Kubernetes API server reports about missing v1alpha1.acme.example.com OpenAPI spec

### ISSUE THREAD

**Issue by EmielBruijntjes** [lordofsystem/cert-manager-webhook-powerdns#86]
After following the installation instructions, the "kube-apiserver" pods running in the "kube-system" namespace, starts to report the following:
```
E1011 16:46:58.203896       1 controller.go:116] loading OpenAPI spec for "v1alpha1.acme.example.com" failed with: OpenAPI spec does not exist
I1011 16:46:58.203933       1 controller.go:129] OpenAPI AggregationController: action for item v1alpha1.acme.example.com: Rate Limited Requeue.
```
The only place where I can find this name is from the "cert-manager-webhook-powerdns/templates/apiservice.yaml" file, which is, generated by helm:
```
# Source: cert-manager-webhook-powerdns/templates/apiservice.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.example.com
  labels:
    app: cert-manager-webhook-powerdns
    chart: cert-manager-webhook-powerdns-0.1.6
    release: cert-manager-webhook-powerdns
    heritage: Helm
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/cert-manager-webhook-powerdns-webhook-tls"
spec:
  group: acme.example.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-webhook-powerdns
    namespace: cert-manager
  version: v1alpha1
```
The above YAML file was a snippet from a YAML file generated by using these commands:
```
helm repo add cert-manager-webhook-powerdns https://lordofsystem.github.io/cert-manager-webhook-powerdns
helm template --namespace cert-manager cert-manager-webhook-powerdns cert-manager-webhook-powerdns/cert-manager-webhook-powerdns --set groupName=acme.example.com
```
Is this something that I did wrong, or an actual issue?
